name: Directory Zipper

on:
  push:
    paths:
      - 'src/**'
      - 'install/**'
      - 'tests/**'
      - 'downloader/**'
      - '.github/workflows/directory-zipper.yml'
      
  workflow_dispatch:
    
jobs:
  zip-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zip directories
        run: |
          DIRECTORIES_TO_ZIP="src install tests"
          OUTPUT_DIRECTORY=release
          ZIP_FILE_NAME=LinuxLogGenerator.zip
          VERSION_FILE_NAME=version.txt
          TEMP_DIRECTORY=temp
      
          mkdir -p $OUTPUT_DIRECTORY
          mkdir -p $TEMP_DIRECTORY
      
          # Increment the version number
          if [ -f $OUTPUT_DIRECTORY/$VERSION_FILE_NAME ]; then
            OLD_VERSION=$(cat $OUTPUT_DIRECTORY/$VERSION_FILE_NAME | cut -d'=' -f2)
            VERSION=$((OLD_VERSION + 1))
          else
            OLD_VERSION="None"
            VERSION=1
          fi
      
          echo "Old version: $OLD_VERSION"
          echo "New version: $VERSION"
          echo "version=$VERSION" > $OUTPUT_DIRECTORY/$VERSION_FILE_NAME
      
          # Copy the directories and the version file to the temp directory
          for DIR in $DIRECTORIES_TO_ZIP; do
            cp -r $DIR $TEMP_DIRECTORY
          done
          cp $OUTPUT_DIRECTORY/$VERSION_FILE_NAME $TEMP_DIRECTORY
      
          # Zip the temp directory
          zip -r $OUTPUT_DIRECTORY/$ZIP_FILE_NAME $TEMP_DIRECTORY
      
          # Remove the temp directory
          rm -rf $TEMP_DIRECTORY

      - name: Add release directory to Git
        run: |
          git add release/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Zip directory $DIRECTORY_TO_ZIP"
          commit_options: "--no-verify"
          
