name: Directory Zipper

on:
  push:
    paths:
      - 'src/**'
      - 'install/**'
      - 'tests/**'
      - 'downloader/**'
      - '.github/workflows/directory-zipper.yml'
      
  workflow_dispatch:
    
jobs:
  zip-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zip directories
        run: |
          DIRECTORIES_TO_ZIP="src install tests"
          OUTPUT_DIRECTORY=release
          ZIP_FILE_NAME=LinuxLogGenerator.zip
          VERSION_FILE_NAME=version.txt
          TEMP_DIRECTORY=temp
      
          mkdir -p $OUTPUT_DIRECTORY
          mkdir -p $TEMP_DIRECTORY

          # Copy the directories to the temp directory
          for DIRECTORY_TO_ZIP in $DIRECTORIES_TO_ZIP; do
            echo "Copying $DIRECTORY_TO_ZIP to $TEMP_DIRECTORY"
            cp -r $DIRECTORY_TO_ZIP $TEMP_DIRECTORY
          done
      
          # Increment the version number.
          if [ -f $OUTPUT_DIRECTORY/$VERSION_FILE_NAME ]; then
            OLD_VERSION=$(cat $OUTPUT_DIRECTORY/$VERSION_FILE_NAME | cut -d'=' -f2)
            VERSION=$((OLD_VERSION + 1))
          else
            OLD_VERSION="None"
            VERSION=1
          fi
      
          echo "Old version: $OLD_VERSION"
          echo "New version: $VERSION"
          echo "version=$VERSION" > $OUTPUT_DIRECTORY/$VERSION_FILE_NAME

          # Zip the version file to release/linuxloggenerator.zip
          echo "Zipping $VERSION_FILE_NAME to $OUTPUT_DIRECTORY/$ZIP_FILE_NAME"
          cd $OUTPUT_DIRECTORY
          zip -r $ZIP_FILE_NAME $VERSION_FILE_NAME
          cd ..


          # Move files from temp directory to zip directory using ZIP -r
          for DIRECTORY_TO_ZIP in $DIRECTORIES_TO_ZIP; do
            echo "Zipping $DIRECTORY_TO_ZIP to $OUTPUT_DIRECTORY/$ZIP_FILE_NAME"
            cd $TEMP_DIRECTORY
            zip -r ../$OUTPUT_DIRECTORY/$ZIP_FILE_NAME $DIRECTORY_TO_ZIP
            cd ..
          done

          # Remove the temp directory
          rm -rf $TEMP_DIRECTORY
          

      - name: Add release directory to Git
        run: |
          git add release/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Zip directory $DIRECTORY_TO_ZIP"
          commit_options: "--no-verify"
          
