name: Directory Zipper

on:
  push:
    paths:
      - 'src/**'
      - 'install/**'
      - 'tests/**'
      
  workflow_dispatch:
    
jobs:
  zip-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        run: python -m unittest tests/test_log_simulator.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Zip directories
        run: |
            APP_DIRECTORY=tools/LinuxLogGenerator
            DIRECTORIES_TO_ZIP="src install"
            OUTPUT_DIRECTORY=build
            ZIP_FILE_NAME=LinuxLogGenerator.zip
        
            mkdir -p $APP_DIRECTORY/$OUTPUT_DIRECTORY
        
            for dir in $DIRECTORIES_TO_ZIP; do
              cd $APP_DIRECTORY/$dir
              zip -r ../../$APP_DIRECTORY/$OUTPUT_DIRECTORY/$ZIP_FILE_NAME .
              cd -
            done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Zip directory $DIRECTORY_TO_ZIP"
          commit_options: "--no-verify"