name: Directory Zipper

on:
  push:
    paths:
      - 'src/**'
      - 'install/**'
      - 'tests/**'
      - 'downloader/**'
      - '.github/workflows/directory-zipper.yml'
      
  workflow_dispatch:
    
jobs:
  zip-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zip directories
        run: |
            DIRECTORIES_TO_ZIP="src install tests"
            OUTPUT_DIRECTORY=package
            ZIP_FILE_NAME=LinuxLogGenerator.zip
            VERSION_FILE_NAME=version.txt
        
            mkdir -p $OUTPUT_DIRECTORY
        
            for dir in $DIRECTORIES_TO_ZIP; do
              cd $dir
              zip -r ../$OUTPUT_DIRECTORY/$ZIP_FILE_NAME .
              cd -
            done
        
            # Increment the version number
            if [ -f $VERSION_FILE_NAME ]; then
              VERSION=$(cat $VERSION_FILE_NAME)
              VERSION=$((VERSION + 1))
            else
              VERSION=1
            fi
        
            echo "version=$VERSION" > $OUTPUT_DIRECTORY/$VERSION_FILE_NAME

      - name: Add package directory to Git
        run: |
          git add package/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Zip directory $DIRECTORY_TO_ZIP"
          commit_options: "--no-verify"
          token: ${{ secrets.PAT }}
