name: Directory Zipper

on:
  push:
    paths:
      - 'src/**'
      - 'install/**'
      - 'tests/**'
      - 'downloader/**'
      - '.github/workflows/directory-zipper.yml'
      
  workflow_dispatch:
    
jobs:
  zip-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zip directories
        run: |
          DIRECTORIES_TO_ZIP="src install tests"
          OUTPUT_DIRECTORY=release
          ZIP_FILE_NAME=LinuxLogGenerator.zip
          VERSION_FILE_NAME=version.txt
      
          mkdir -p $OUTPUT_DIRECTORY
      
          # Increment the version number
          if [ -f $OUTPUT_DIRECTORY/$VERSION_FILE_NAME ]; then
            OLD_VERSION=$(cat $OUTPUT_DIRECTORY/$VERSION_FILE_NAME | cut -d'=' -f2)
            VERSION=$((OLD_VERSION + 1))
          else
            OLD_VERSION="None"
            VERSION=1
          fi
      
          echo "Old version: $OLD_VERSION"
          echo "New version: $VERSION"
          echo "version=$VERSION" > $OUTPUT_DIRECTORY/$VERSION_FILE_NAME
      
          # Change to the GitHub workspace directory
          cd $GITHUB_WORKSPACE
      
          for DIR in $DIRECTORIES_TO_ZIP; do
            cd $DIR
            zip -r ../$OUTPUT_DIRECTORY/$ZIP_FILE_NAME . -x "*$OUTPUT_DIRECTORY/*"
            cd ..
          done
          
          zip -j -u $OUTPUT_DIRECTORY/$ZIP_FILE_NAME $OUTPUT_DIRECTORY/$VERSION_FILE_NAME

      - name: Add release directory to Git
        run: |
          git add release/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Zip directory $DIRECTORY_TO_ZIP"
          commit_options: "--no-verify"
          
